DROP TABLE IF EXISTS public."Petro_Caribe_Analysis";
CREATE TABLE public."Petro_Caribe_Analysis"
(
	"Country" text,
	"Analysis" real,
	"Extended Credit Facility" real,
	"Agreement" text,
	"CAB 2005 (%GSP)" real,
	"Debt to GDP Ratio 2005" real,
	"Nominal GDP 2005 (USD bil)" real,
	"Total Public Debt 2005 (USD bil)" real,
	"GDP Growth 2013" real,
	"CAB 2013 (%GDP)" real,
	"Debt to GDP Ratio 2013" real,
	"IMF Program 2013" text,
	"Inflation 2013 (avg)" real,
	"Nominal GDP 2013 (USD bil)" real,
	"Total Public Debt 2013 (USD bil)" real,
	"Share PetroCaribe DSP" real,
	"Annual Financing weighted (%GDP)" real,
	"Stock of Debt weighted (%GDP)" real,
	"Annual Financing 2012 (%GDP)" real,
	"Stock of Debt 2012 (%GDP)" real,
	"PC Debt to GDP weighted" real,
	"Share of Total Debt weighted" real,
	"Debt to Paris Club (USD mil)" real,
	"Debt to Paris Club (% Total Debt)" real,
	"Debt to US (USD mil)" real,
	"Debt to US (% Total Debt)" real,
	"Debt to AUS (USD mil)" real,
	"Debt to AUT (USD mil)" real,
	"Debt to BEL (USD mil)" real,
	"Debt to CAN (USD mil)" real,
	"Debt to DNK (USD mil)" real,
	"Debt to FIN (USD mil)" real,
	"Debt to FRA (USD mil)" real,
	"Debt to GER (USD mil)" real,
	"Debt to ITA (USD mil)" real,
	"Debt to JPN (USD mil)" real,
	"Debt to NLD (USD mil)" real,
	"Debt to NOR (USD mil)" real,
	"Debt to RUS (USD mil)" real,
	"Debt to SPA (USD mil)" real,
	"Debt to SWE (USD mil)" real,
	"Debt to SWI (USD mil)" real,
	"Debt to UK (USD mil)" real,
	"Debt-to-GDP Index" real,
	"AF Index" real,
	"Main Index" real,
	"Cell" text
);

set client_encoding to 'UTF-8';

COPY "Petro_Caribe_Analysis" FROM 'C:\OpenGeo\webapps\caribbean-energy\sql\Petro_Caribe_Analysis.csv' DELIMITER ',' CSV;